if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "juparor@gmail.com"
  git config --global user.name "juparor"

  git remote add release "https://${GH_TOKEN}@github.com/juparor/GestionVisualizacionDelProgramaEGC1718App.git"

  git push -d release latest
  git tag -d latest
  git tag -a "latest" -m "[Autogenerated] This is the latest version pushed to the master branch."
  git push release --tags
fi